aws:
  access-key:
  secret-key:
  region:
  s3-bucket-name:
  multipart-min-part-size:

# Define below Camel S3 Properties when below condition is not available
## useProfileCredentialsProvider=true
camel:
  component:
    aws2-s3:
      access-key:
      secret-key:
      region:

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/dev